/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.carreradecaballos.interfaz;

import co.carreradecaballos.interfaz.logica.Caballos;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Usuario
 */
public class ICarrera extends javax.swing.JFrame {

    /**
     * Creates new form Carrera
     */
    public ICarrera() {
        initComponents();
    }
    
    public JLabel getlbl1(){
        return lbl1;
    }
    public JLabel getlbl2(){
        return lbl2;
    }
    public JLabel getlbl3(){
        return lbl3;
    }
    public JLabel getlbl4(){
        return lbl4;
    }
    public JLabel getlbl5(){
        return lbl5;
    }
    public JLabel getlbl6(){
        return lbl6;
    }
    public JLabel getlbl7(){
        return lbl7;
    }
    public JLabel getlbl8(){
        return lbl8;
    }
    public JLabel getlbl9(){
        return lbl9;
    }
    public JLabel getlbl10(){
        return lbl10;
    }
    public JLabel getlblBarrera(){
        return lblBarrera;
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnIniciarCarrera = new javax.swing.JButton();
        lbl10 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lblBarrera = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnIniciarCarrera.setText("INICIAR CARRERA");
        jbtnIniciarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIniciarCarreraActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnIniciarCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 600, 185, -1));

        lbl10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/carreradecaballos/interfaz/recursos/Imagen1.png"))); // NOI18N
        jPanel1.add(lbl10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 513, -1, -1));

        lbl9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/carreradecaballos/interfaz/recursos/Imagen1.png"))); // NOI18N
        jPanel1.add(lbl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 456, -1, -1));

        lbl8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/carreradecaballos/interfaz/recursos/Imagen1.png"))); // NOI18N
        jPanel1.add(lbl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 399, -1, -1));

        lbl7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/carreradecaballos/interfaz/recursos/Imagen1.png"))); // NOI18N
        jPanel1.add(lbl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 342, -1, -1));

        lbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/carreradecaballos/interfaz/recursos/Imagen1.png"))); // NOI18N
        jPanel1.add(lbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 285, -1, -1));

        lbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/carreradecaballos/interfaz/recursos/Imagen1.png"))); // NOI18N
        jPanel1.add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 228, -1, -1));

        lbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/carreradecaballos/interfaz/recursos/Imagen1.png"))); // NOI18N
        jPanel1.add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 171, -1, -1));

        lbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/carreradecaballos/interfaz/recursos/Imagen1.png"))); // NOI18N
        jPanel1.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 114, -1, -1));

        lbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/carreradecaballos/interfaz/recursos/Imagen1.png"))); // NOI18N
        jPanel1.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, -1, -1));

        lbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/carreradecaballos/interfaz/recursos/Imagen1.png"))); // NOI18N
        jPanel1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        lblBarrera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        jPanel1.add(lblBarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, -1, 570));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/carreradecaballos/interfaz/recursos/Imagen2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 840, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\LA MATRIX\\Desktop\\CarreraCaballos-master\\src\\co\\carreradecaballos\\interfaz\\recursos\\Imagen2.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/carreradecaballos/interfaz/recursos/Imagen2.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 840, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/carreradecaballos/interfaz/recursos/Imagen2.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 840, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/carreradecaballos/interfaz/recursos/Imagen2.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 840, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/carreradecaballos/interfaz/recursos/Imagen2.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 840, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/carreradecaballos/interfaz/recursos/Imagen2.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 840, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/carreradecaballos/interfaz/recursos/Imagen2.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 840, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/carreradecaballos/interfaz/recursos/Imagen2.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 840, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/carreradecaballos/interfaz/recursos/Imagen2.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 840, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnIniciarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIniciarCarreraActionPerformed
        // TODO add your handling code here:
        lbl1.setLocation(0,lbl1.getLocation().y);
        lbl2.setLocation(0,lbl2.getLocation().y);
        lbl3.setLocation(0,lbl3.getLocation().y);
        lbl4.setLocation(0,lbl4.getLocation().y);
        lbl5.setLocation(0,lbl5.getLocation().y);
        lbl6.setLocation(0,lbl6.getLocation().y);
        lbl7.setLocation(0,lbl7.getLocation().y);
        lbl8.setLocation(0,lbl8.getLocation().y);
        lbl9.setLocation(0,lbl9.getLocation().y);
        lbl10.setLocation(0,lbl10.getLocation().y);
        
        Caballos hilo1 = null;
        try {
            hilo1 = new Caballos (lbl1,this);
        } catch (IOException ex) {
            Logger.getLogger(ICarrera.class.getName()).log(Level.SEVERE, null, ex);
        }
        Caballos hilo2 = null;
        try {
            hilo2 = new Caballos (lbl2,this);
        } catch (IOException ex) {
            Logger.getLogger(ICarrera.class.getName()).log(Level.SEVERE, null, ex);
        }
        Caballos hilo3 = null;
        try {
            hilo3 = new Caballos (lbl3,this);
        } catch (IOException ex) {
            Logger.getLogger(ICarrera.class.getName()).log(Level.SEVERE, null, ex);
        }
        Caballos hilo4 = null;
        try {
            hilo4 = new Caballos (lbl4,this);
        } catch (IOException ex) {
            Logger.getLogger(ICarrera.class.getName()).log(Level.SEVERE, null, ex);
        }
        Caballos hilo5 = null;
        try {
            hilo5 = new Caballos (lbl5,this);
        } catch (IOException ex) {
            Logger.getLogger(ICarrera.class.getName()).log(Level.SEVERE, null, ex);
        }
        Caballos hilo6 = null;
        try {
            hilo6 = new Caballos (lbl6,this);
        } catch (IOException ex) {
            Logger.getLogger(ICarrera.class.getName()).log(Level.SEVERE, null, ex);
        }
        Caballos hilo7 = null;
        try {
            hilo7 = new Caballos (lbl7,this);
        } catch (IOException ex) {
            Logger.getLogger(ICarrera.class.getName()).log(Level.SEVERE, null, ex);
        }
        Caballos hilo8 = null;
        try {
            hilo8 = new Caballos (lbl8,this);
        } catch (IOException ex) {
            Logger.getLogger(ICarrera.class.getName()).log(Level.SEVERE, null, ex);
        }
        Caballos hilo9 = null;
        try {
            hilo9 = new Caballos (lbl9,this);
        } catch (IOException ex) {
            Logger.getLogger(ICarrera.class.getName()).log(Level.SEVERE, null, ex);
        }
        Caballos hilo10 = null;
        try {
            hilo10 = new Caballos (lbl10,this);
        } catch (IOException ex) {
            Logger.getLogger(ICarrera.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        hilo1.start();
        hilo2.start();
        hilo3.start();
        hilo4.start();
        hilo5.start();
        hilo6.start();
        hilo7.start();
        hilo8.start();
        hilo9.start();
        hilo10.start();
        
        
    }//GEN-LAST:event_jbtnIniciarCarreraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ICarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ICarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ICarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ICarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ICarrera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnIniciarCarrera;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblBarrera;
    // End of variables declaration//GEN-END:variables
}
